version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID 



jobs:
  to_f_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run:
          name: on previous failure
          command: echo the previous job failed
          when: on_fail

workflows:
  say-hello-workflow:
    jobs:
      - to_f_job
