version: 2.1

commands:
  save_node_package_to_cache:
    steps:
      - save_cache:
          key:  npm_packages
          paths: [/node_modules]
  restore_packages:
    steps:
      - restore_chache:
        - keys:
          - npm_packages

jobs:
  build:
    docker: $defaultImage
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: save_cache
      - run: npm run lint


  test:
    <<: *defaultImage
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: restore_chache
      - run: npm i
      - run: npm run test


  analyze:
    <<: *defaultImage
    steps:
      - checkout
      - run: restore_chache
      - run: npm i
      - run: npm audit
  

workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]
