version: 2.1

commands:
  save_node_package_to_cache:
    steps:
      - save_cache:
          key:  npm_packages
          paths: 
            - ./node_modules
  restore_packages:
    steps:
      - restore_cache:
          keys:
            - npm_packages

jobs:
  build:
    docker: 
      - image: &defaultImage circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_node_package_to_cache
      - run: npm run lint

  test:
    docker:
      - image: *defaultImage
    steps:
      - checkout
      - restore_packages
      - run: npm i
      - run: npm run test


  analyze:
    docker:
      - image: *defaultImage
    steps:
      - checkout
      - restore_packages
      - run: npm i
      - run: npm audit
  

workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]
